### ISSUE TITLE
Taller de flutter

### ISSUE THREAD

**Issue by JJSS2609** [ISCOUTB/DH-NovelNook#3]

**Comment by JJSS2609** [comment]
FLUTTER es un framework de desarrollo de interfaces de usuario creado por Google que permite construir aplicaciones nativas para iOS, Android, e incluso Web y escritorio desde una única base de código. Lanzado en 2018, Flutter ha ganado popularidad rápidamente gracias a su eficiencia y la capacidad de crear aplicaciones visualmente atractivas con un alto rendimiento.

Flutter funciona de manera diferente a otros frameworks. Su arquitectura se basa en:

1.-Dart: Es el lenguaje de programación utilizado por Flutter, el cual se compila a código nativo, mejorando el rendimiento.
2.-Motor de Flutter: Basado en Skia, el motor gráfico que Flutter utiliza para renderizar la interfaz de usuario.
3.-Widgets: En Flutter, todo es un widget. Desde un simple texto hasta un diseño complejo, todo se construye a partir de estos bloques modulares.

VENTAJAS 

1.- Un solo código base permite crear aplicaciones para múltiples plataformas.
2.- Dado que Flutter no depende de componentes nativos y renderiza su propia interfaz de usuario, ofrece un rendimiento casi nativo.
3.-Con la función Hot Reload, los cambios en el código se reflejan casi instantáneamente, lo que acelera el desarrollo.
4.- Los widgets de Flutter permiten crear interfaces de usuario altamente personalizadas y consistentes en todas las plataformas.

DESVENTAJAS

1.- Las aplicaciones creadas con Flutter pueden ser más pesadas en comparación con las desarrolladas nativamente.
2.- Aunque Flutter tiene una comunidad en expansión, algunas bibliotecas y paquetes aún están en desarrollo o no están tan optimizados como los de otros frameworks.

**Comment by Benyamye** [comment]
Aprendiendo de Flutter y mas 

Flutter es un framework de código abierto que se usa para crear aplicaciones multiplataforma nativas a partir de un único código base. este se ha convertido rápidamente en una herramienta popular para el desarrollo de aplicaciones móviles, web y de escritorio.

Algunas características más importantes que pude encontrar de este fueron:
-Desarrollo multiplataforma: Con flutter, puedes escribir código una vez y ejecutarlo en múltiples plataformas, incluyendo iOS, Android, web.
-Renderizado propio: Flutter renderiza cada píxel para que la UI luzca consistente en todos los dispositivos, para esto se usa Skia e Impeller
-Hot Reload: Permite ver los cambios en el código reflejados instantáneamente en la aplicación en ejecución, haciendo que no perdamos el estado actual.
-Widgets personalizables: Todo en flutter es un widget, y estos pueden ser altamente personalizados.
-Rendimiento nativo: Las aplicaciones flutter se compilan en código nativo, lo que resulta en un rendimiento comparable al de las aplicaciones nativas tradicionales.

Encontrre que flutter utiliza Dart como su lenguaje de programación principal. Este lenguaje también desarrollado por Google.

Lo siguiente que estuve buscando es como descargar flutter para hacer algunas pruebas, me vi algunos tutoriales de cómo hacerlo y también estuve viendo como aprender su lenguaje de programación.

**Comment by Jesus-david-contreras** [comment]
He estado estudiando Flutter, que es un framework de desarrollo de interfaces de usuario creado por Google. Lo interesante de Flutter es que permite construir aplicaciones nativas para iOS, Android, web y escritorio a partir de una sola base de código. Además, utiliza Dart como su lenguaje de programación, lo que facilita la compilación directa a código nativo, mejorando el rendimiento.

He aprendido que Flutter se basa en tres elementos principales: el lenguaje Dart, su propio motor gráfico para renderizar la interfaz sin depender de los componentes nativos, y su sistema de widgets modulares que permiten personalizar la apariencia y funcionalidad de las aplicaciones de manera eficiente. También he investigado cómo instalar Flutter, cómo empezar a trabajar con sus herramientas y qué ventajas y limitaciones ofrece para el desarrollo multiplataforma.


Sin embargo, también he identificado varias desventajas que es importante considerar:

Curva de aprendizaje para Dart: Aunque Dart es un lenguaje relativamente fácil de aprender, no es tan popular como otros lenguajes, por lo que puede haber una curva de aprendizaje más pronunciada para los desarrolladores que no están familiarizados con él. Además, la cantidad de recursos y documentación puede ser limitada en comparación con otros lenguajes más establecidos.

Mayor consumo de recursos: Aunque Flutter ofrece un rendimiento excelente, su enfoque en el renderizado independiente puede hacer que las aplicaciones utilicen más recursos de hardware, como memoria y CPU, en comparación con soluciones nativas.

Carga inicial más lenta: Debido a la arquitectura de Flutter y la forma en que maneja los widgets, algunas aplicaciones pueden experimentar un tiempo de carga inicial más lento en comparación con aplicaciones nativas, lo que puede afectar la experiencia del usuario.
