### ISSUE TITLE
definir interfaz para la app web

### ISSUE THREAD

**Issue by JJSS2609** [ISCOUTB/DH-NovelNook#5]

**Comment by Benyamye** [comment]
Wireframe de la App, realice un pequeño bosquejo de la idea que tenía en mente, puede estar sujeto a cambios, si a mis compañeros les gusta la idea o si les gustaría cambiar el diseño y/o agregar más cosas o en su casa quitarlas

Primero tenemos la creación de la cuenta, lo necesario, usuario, contraseña, correo 

![Image](https://github.com/user-attachments/assets/5fc495b5-e71b-4c83-94f6-75a34348b495)

Tenemos también, que usuario eres, tu correo y que libros te gustan, la parte del usuario y contraseña puede omitirse debido a que ya esta en el paso anterior

![Image](https://github.com/user-attachments/assets/cf14fc18-2477-43d9-be5a-88032c326b43)

Por último, tendríamos el inicio 

![Image](https://github.com/user-attachments/assets/d154e051-9d9a-4a92-b8c3-1a83c2b6f8e4)

**Comment by jairoserrano** [comment]
adelante
